import dynamic from "next/dynamic";
import { getRawCode } from "@/utils/rawCode";

export const registry = [
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'agency',
        version: '01',
        id: 'shadcn-layout-hero-agency-01',
        tags: ['badge', 'button', 'card', 'stats'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/agency/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/agency/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'blog',
        version: '01',
        id: 'shadcn-layout-hero-blog-01',
        tags: ['avatar', 'badge', 'button', 'card', 'image'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/blog/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/blog/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'blog',
        version: '02',
        id: 'shadcn-layout-hero-blog-02',
        tags: ['avatar', 'badge', 'button', 'card'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/blog/02')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/blog/02.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'blog',
        version: '03',
        id: 'shadcn-layout-hero-blog-03',
        tags: ['avatar', 'badge', 'button', 'card', 'input', 'list', 'image'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/blog/03')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/blog/03.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'blog',
        version: '04',
        id: 'shadcn-layout-hero-blog-04',
        tags: ['badge', 'button', 'input', 'stats'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/blog/04')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/blog/04.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'blog',
        version: '05',
        id: 'shadcn-layout-hero-blog-05',
        tags: ['avatar', 'badge', 'button', 'carousel', 'image'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/blog/05')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/blog/05.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'blog',
        version: '06',
        id: 'shadcn-layout-hero-blog-06',
        tags: ['avatar', 'badge', 'button', 'card', 'image'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/blog/06')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/blog/06.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'blog',
        version: '07',
        id: 'shadcn-layout-hero-blog-07',
        tags: ['badge', 'button', 'card', 'stats'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/blog/07')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/blog/07.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'business',
        version: '01',
        id: 'shadcn-layout-hero-business-01',
        tags: ['badge', 'button', 'card', 'list', 'stats'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/business/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/business/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'ecommerce',
        version: '01',
        id: 'shadcn-layout-hero-ecommerce-01',
        tags: ['badge', 'button', 'card', 'image'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/ecommerce/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/ecommerce/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'education',
        version: '01',
        id: 'shadcn-layout-hero-education-01',
        tags: ['avatar', 'badge', 'button', 'card', 'image', 'stats'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/education/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/education/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'landing',
        version: '01',
        id: 'shadcn-layout-hero-landing-01',
        tags: ['avatar', 'badge', 'button', 'input'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/landing/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/landing/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'landing',
        version: '02',
        id: 'shadcn-layout-hero-landing-02',
        tags: ['avatar', 'badge', 'button', 'input', 'list'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/landing/02')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/landing/02.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'news',
        version: '01',
        id: 'shadcn-layout-hero-news-01',
        tags: ['badge', 'button', 'card', 'image', 'list'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/news/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/news/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'news',
        version: '02',
        id: 'shadcn-layout-hero-news-02',
        tags: ['avatar', 'badge', 'button', 'card', 'image', 'stats'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/news/02')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/news/02.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'portfolio',
        version: '01',
        id: 'shadcn-layout-hero-portfolio-01',
        tags: ['badge', 'button', 'image'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/portfolio/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/portfolio/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'portfolio',
        version: '02',
        id: 'shadcn-layout-hero-portfolio-02',
        tags: ['avatar', 'badge', 'button'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/portfolio/02')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/portfolio/02.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'portfolio',
        version: '03',
        id: 'shadcn-layout-hero-portfolio-03',
        tags: ['avatar', 'badge', 'button'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/portfolio/03')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/portfolio/03.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'restaurant',
        version: '01',
        id: 'shadcn-layout-hero-restaurant-01',
        tags: ['badge', 'button', 'card', 'image', 'stats'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/restaurant/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/restaurant/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'saas',
        version: '01',
        id: 'shadcn-layout-hero-saas-01',
        tags: ['avatar', 'badge', 'button', 'card'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/saas/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/saas/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'startup',
        version: '01',
        id: 'shadcn-layout-hero-startup-01',
        tags: ['avatar', 'badge', 'button', 'input'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/startup/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/startup/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'startup',
        version: '02',
        id: 'shadcn-layout-hero-startup-02',
        tags: ['badge', 'button', 'image', 'list'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/startup/02')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/startup/02.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'startup',
        version: '03',
        id: 'shadcn-layout-hero-startup-03',
        tags: ['badge', 'button', 'card'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/startup/03')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/startup/03.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'startup',
        version: '04',
        id: 'shadcn-layout-hero-startup-04',
        tags: ['badge', 'button', 'stats'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/startup/04')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/startup/04.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'layout',
        block: 'hero',
        variant: 'startup',
        version: '05',
        id: 'shadcn-layout-hero-startup-05',
        tags: ['badge', 'button', 'card', 'stats'],
        code: dynamic(() => import('@/ui-library/shadcn/layout/hero/startup/05')),
        source: async () => await getRawCode('src/ui-library/shadcn/layout/hero/startup/05.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'navigation',
        block: 'navbar',
        variant: 'general',
        version: '01',
        id: 'shadcn-navigation-navbar-general-01',
        tags: ['button'],
        code: dynamic(() => import('@/ui-library/shadcn/navigation/navbar/general/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/navigation/navbar/general/01.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'navigation',
        block: 'navbar',
        variant: 'general',
        version: '02',
        id: 'shadcn-navigation-navbar-general-02',
        tags: ['button'],
        code: dynamic(() => import('@/ui-library/shadcn/navigation/navbar/general/02')),
        source: async () => await getRawCode('src/ui-library/shadcn/navigation/navbar/general/02.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'navigation',
        block: 'navbar',
        variant: 'general',
        version: '03',
        id: 'shadcn-navigation-navbar-general-03',
        tags: ['button'],
        code: dynamic(() => import('@/ui-library/shadcn/navigation/navbar/general/03')),
        source: async () => await getRawCode('src/ui-library/shadcn/navigation/navbar/general/03.tsx'),
    },
    {
        uiLibrary: 'shadcn',
        category: 'utility',
        block: 'codeblock',
        variant: 'prism',
        version: '01',
        id: 'shadcn-utility-codeblock-prism-01',
        tags: ['code'],
        code: dynamic(() => import('@/ui-library/shadcn/utility/codeblock/prism/01')),
        source: async () => await getRawCode('src/ui-library/shadcn/utility/codeblock/prism/01.tsx'),
    },
]

export default registry;
export type Block = (typeof registry)[number];
